services:
  db:
    image: posgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: hack-connect
  server:
    image:
    environment:
      SPRING_PROFILES_ACTIVE: prod