server:
    port: 80

spring:
    datasource:
        #    url: jdbc:postgresql://raspberrypi:5432/
        url: jdbc:postgresql://raspberrypi:5432/hackconnect
        username: postgres
        #    password: 123456
        password: "123456"
    jpa:
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false