server:
    port: 80

spring:
    datasource:
        #    url: jdbc:postgresql://172.16.24.120:5432/
        url: jdbc:postgresql://localhost:5432/hack_connect
        username: postgres
        #    password: 123456
        password: password
    jpa:
        hibernate:
            ddl-auto: update
    flyway:
        enabled: false